tasks:
  - init: |
      npm install
      cd frontend
      npm install
    command: npm run dev

ports:
  - port: 5000
    visibility: public
  - port: 3000
    visibility: public
    onOpen: open-browser
